#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

# the "app_lucky_number" route name is not important yet

#app_lucky_number: 
   # path: /lucky/number #la route du chemin url
    #controller: App\Controller\LuckyController::number #le nom de la class sans le php avec : on lui demande de declancher la function numer de la classe luckycontoller
